//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Invoice.Models.Dao
{
    using System;
	using System.ComponentModel.DataAnnotations;
    using System.Collections.Generic;
    
    public abstract partial class Company
    {
        [Display(Name="Id")]                     public virtual int        Id                   { get; set; }
        [Display(Name="Namn")]                   public virtual string     Namn                 { get; set; }
        [Display(Name="Org. nummer")]            public virtual long       Org__nummer          { get; set; }
        [Display(Name="Momsreg. nummer")]        public virtual long       Momsreg__nummer      { get; set; }
        [Display(Name="Adress")]                 public virtual string     Adress               { get; set; }
        [Display(Name="Postnummer")]             public virtual string     Postnummer           { get; set; }
        [Display(Name="Land")]                   public virtual string     Land                 { get; set; }
        [Display(Name="Epost")][DataType(DataType.EmailAddress)] public virtual string     Epost                { get; set; }
        [Display(Name="Telefon")][DataType(DataType.PhoneNumber)] public virtual long       Telefon              { get; set; }
        [Display(Name="Hemsida")][DataType(DataType.Url)] public virtual string     Hemsida              { get; set; }
        [Display(Name="Logotyp")][DataType(DataType.ImageUrl)] public virtual string     Logotyp              { get; set; }
        [Display(Name="Övrig information")]      public virtual string     Övrig___information  { get; set; }
        [Display(Name="Ort")]                    public virtual string     Ort                  { get; set; }
    }
}
