//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Invoice.Models.Dao
{
    using System;
	using System.ComponentModel.DataAnnotations;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        [Display(Name="Id")]                     public virtual int        Id                   { get; set; }
        [Display(Name="Namn")]                   public virtual string     Namn                 { get; set; }
        [Display(Name="Address")]                public virtual string     Address              { get; set; }
        [Display(Name="Referenspersoner")]       public virtual string     ReferensPersoner     { get; set; }
    
          public virtual Project Projects { get; set; }
    }
}
