//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Invoice.Models.Dao
{
    using System;
	using System.ComponentModel.DataAnnotations;
    using System.Collections.Generic;
    
    public abstract partial class Dailyreport
    {
        [Display(Name="Id")]                     public virtual int        Id                   { get; set; }
        [Display(Name="Datum")][DataType(DataType.DateTime)] public virtual System.DateTime Datum                { get; set; }
        [Display(Name="Kund")]                   public virtual string     Kund                 { get; set; }
        [Display(Name="Projekt")]                public virtual string     Projekt              { get; set; }
        [Display(Name="Anställd")]               public virtual string     Anställd             { get; set; }
        [Display(Name="Starttid")][DataType(DataType.Time)] public virtual System.TimeSpan StartTid             { get; set; }
        [Display(Name="Sluttid")][DataType(DataType.Time)] public virtual System.TimeSpan SlutTid              { get; set; }
    
          public virtual Employee Employee { get; set; }
          public virtual Project Projekts { get; set; }
    }
}
