//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Invoice.Models.Dao
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ProjektarbeteEntities : DbContext
    {
        public ProjektarbeteEntities()
            : base("name=ProjektarbeteEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<        Company>       Companies { get; set; }
        public virtual DbSet<       Customer>       Customers { get; set; }
        public virtual DbSet<    Dailyreport>    Dailyreports { get; set; }
        public virtual DbSet<       Employee>       Employees { get; set; }
        public virtual DbSet<        Project>        Projects { get; set; }
    }
}
