//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Invoice.Models.Dao
{
    using System;
	using System.ComponentModel.DataAnnotations;
    using System.Collections.Generic;
    
    public abstract partial class Project
    {
        public Project()
        {
            this.Customer = new HashSet<Customer>();
            this.Dailyreports = new HashSet<Dailyreport>();
        }
    
        [Display(Name="Id")]                     public virtual int        Id                   { get; set; }
        [Display(Name="Namn")]                   public virtual string     Namn                 { get; set; }
        [Display(Name="Kund")]                   public virtual string     Kund                 { get; set; }
        [Display(Name="Startdatum")][DataType(DataType.DateTime)] public virtual System.DateTime StartDatum           { get; set; }
        [Display(Name="Slutdatum")][DataType(DataType.DateTime)] public virtual System.DateTime SlutDatum            { get; set; }
        [Display(Name="Beskrivning")]            public virtual string     Beskrivning          { get; set; }
    
          public virtual ICollection<Customer> Customer { get; set; }
          public virtual ICollection<Dailyreport> Dailyreports { get; set; }
    }
}
